CREATE TABLE WAITING_INV_ITEMS (
	"ID" INTEGER PRIMARY KEY,
    "WAITING_PRODS_ID" INTEGER,
	"BUYING_PRICE" REAL,
	"DATE" TEXT,
	"DESC_WEB" TEXT,
	"SELL_PRICE" REAL,
	"SIZE" TEXT,
	"ITEM_ORIG_PRICE" TEXT,
	"ITEM_PRICE" TEXT,
	"ITEM_TAX" TEXT,
	"ITEM_DISCOUNT" TEXT,
	"ITEM_TOTAL" TEXT,
	"ITEM_STATUS" TEXT,
	"ORD_COUNT" INTEGER,
	"VALID" INTEGER
    );