CREATE TABLE WAITING_PRODUCTS (
	"ID" INTEGER PRIMARY KEY,
	"COMMENT" TEXT,
	"VALID" INTEGER,
	
	"INVOICE_NR" TEXT,
	"SKU" TEXT,
	"INV_SKU" TEXT,
	"DESCRIPTION" TEXT,
	"BUYING_PRICE" REAL,
	"ORDER_DATE" TEXT,
	"DESCRIPTION_WEB" TEXT,
	"SELL_PRICE" REAL,
	"SIZE" TEXT,
	"ITEM_ORIG_PRICE" TEXT,
	"ITEM_PRICE" TEXT,
	"ITEM_TAX" TEXT,
	"ITEM_DISCOUNT" TEXT,
	"DISCOUNT_POHODA" TEXT,
	"ITEM_TOTAL" TEXT,
	"ITEM_STATUS" TEXT,
	"ORD_COUNT" TEXT,
	"STORAGE" TEXT
    );