//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46589457")]
        public string ActiveStyle_ICO {
            get {
                return ((string)(this["ActiveStyle_ICO"]));
            }
            set {
                this["ActiveStyle_ICO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DueDateAdd {
            get {
                return ((int)(this["DueDateAdd"]));
            }
            set {
                this["DueDateAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0200")]
        public string BankCode {
            get {
                return ((string)(this["BankCode"]));
            }
            set {
                this["BankCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0308")]
        public string ConstSym {
            get {
                return ((string)(this["ConstSym"]));
            }
            set {
                this["ConstSym"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VUB")]
        public string Bank {
            get {
                return ((string)(this["Bank"]));
            }
            set {
                this["Bank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UD")]
        public string ClasifficationVAT {
            get {
                return ((string)(this["ClasifficationVAT"]));
            }
            set {
                this["ClasifficationVAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Accounting {
            get {
                return ((string)(this["Accounting"]));
            }
            set {
                this["Accounting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float DPH_percent {
            get {
                return ((float)(this["DPH_percent"]));
            }
            set {
                this["DPH_percent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SK")]
        public string TypePrice {
            get {
                return ((string)(this["TypePrice"]));
            }
            set {
                this["TypePrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03")]
        public string Storage {
            get {
                return ((string)(this["Storage"]));
            }
            set {
                this["Storage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shipping")]
        public string ShippingCode {
            get {
                return ((string)(this["ShippingCode"]));
            }
            set {
                this["ShippingCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.232")]
        public string ExRateCzk {
            get {
                return ((string)(this["ExRateCzk"]));
            }
            set {
                this["ExRateCzk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("281.42")]
        public string ExRateHuf {
            get {
                return ((string)(this["ExRateHuf"]));
            }
            set {
                this["ExRateHuf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.1088")]
        public string ExRatePln {
            get {
                return ((string)(this["ExRatePln"]));
            }
            set {
                this["ExRatePln"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cena za dopravu")]
        public string ShipTextSkk {
            get {
                return ((string)(this["ShipTextSkk"]));
            }
            set {
                this["ShipTextSkk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cena za dopravu")]
        public string ShipTextCzk {
            get {
                return ((string)(this["ShipTextCzk"]));
            }
            set {
                this["ShipTextCzk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Szállítási és csomaglási költség")]
        public string ShipTextHuf {
            get {
                return ((string)(this["ShipTextHuf"]));
            }
            set {
                this["ShipTextHuf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Koszt dostawy")]
        public string ShipTextPln {
            get {
                return ((string)(this["ShipTextPln"]));
            }
            set {
                this["ShipTextPln"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.99")]
        public string ShipPriceSkk {
            get {
                return ((string)(this["ShipPriceSkk"]));
            }
            set {
                this["ShipPriceSkk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string ShipPriceCzk {
            get {
                return ((string)(this["ShipPriceCzk"]));
            }
            set {
                this["ShipPriceCzk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("990")]
        public string ShipPriceHuf {
            get {
                return ((string)(this["ShipPriceHuf"]));
            }
            set {
                this["ShipPriceHuf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public string ShipPricePln {
            get {
                return ((string)(this["ShipPricePln"]));
            }
            set {
                this["ShipPricePln"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public string TaxSkk {
            get {
                return ((string)(this["TaxSkk"]));
            }
            set {
                this["TaxSkk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.19")]
        public string TaxCzk {
            get {
                return ((string)(this["TaxCzk"]));
            }
            set {
                this["TaxCzk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.25")]
        public string TaxHuf {
            get {
                return ((string)(this["TaxHuf"]));
            }
            set {
                this["TaxHuf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.15")]
        public string TaxPln {
            get {
                return ((string)(this["TaxPln"]));
            }
            set {
                this["TaxPln"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml")]
        public string ExchRateXMLAddress {
            get {
                return ((string)(this["ExchRateXMLAddress"]));
            }
            set {
                this["ExchRateXMLAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SubProductLength {
            get {
                return ((int)(this["SubProductLength"]));
            }
            set {
                this["SubProductLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string PartnerSports {
            get {
                return ((string)(this["PartnerSports"]));
            }
            set {
                this["PartnerSports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string PartnerMandM {
            get {
                return ((string)(this["PartnerMandM"]));
            }
            set {
                this["PartnerMandM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public string PartnerLabel {
            get {
                return ((string)(this["PartnerLabel"]));
            }
            set {
                this["PartnerLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSkkSerie {
            get {
                return ((bool)(this["UseSkkSerie"]));
            }
            set {
                this["UseSkkSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCzkSerie {
            get {
                return ((bool)(this["UseCzkSerie"]));
            }
            set {
                this["UseCzkSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseHufSerie {
            get {
                return ((bool)(this["UseHufSerie"]));
            }
            set {
                this["UseHufSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsePlnSerie {
            get {
                return ((bool)(this["UsePlnSerie"]));
            }
            set {
                this["UsePlnSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13SVF")]
        public string SkkSerie {
            get {
                return ((string)(this["SkkSerie"]));
            }
            set {
                this["SkkSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13CVF")]
        public string CzkSerie {
            get {
                return ((string)(this["CzkSerie"]));
            }
            set {
                this["CzkSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13HVF")]
        public string HufSerie {
            get {
                return ((string)(this["HufSerie"]));
            }
            set {
                this["HufSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13PVF")]
        public string PlnSerie {
            get {
                return ((string)(this["PlnSerie"]));
            }
            set {
                this["PlnSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09")]
        public string CancelledStorage {
            get {
                return ((string)(this["CancelledStorage"]));
            }
            set {
                this["CancelledStorage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ER")]
        public string CiarKodPrefix {
            get {
                return ((string)(this["CiarKodPrefix"]));
            }
            set {
                this["CiarKodPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SK")]
        public string CiarKodPostfix {
            get {
                return ((string)(this["CiarKodPostfix"]));
            }
            set {
                this["CiarKodPostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89069766")]
        public long CiarKod {
            get {
                return ((long)(this["CiarKod"]));
            }
            set {
                this["CiarKod"] = value;
            }
        }
    }
}
